version: '3.7'

services:
  workspace:
    image: local/node:12.7.0
    volumes:
      - v-sync-rhs:/app
    ports:
      - "8080:8080"
    tty: true
    command: /bin/bash

volumes:
  v-sync-rhs:
    external: true
